import PDFDocument from "pdfkit";
import { CaseState } from "./store.ts";

export function generateEvidencePdf(caseState: CaseState, res: any) {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=evidence_pack_${caseState.case_id}.pdf`);

  doc.pipe(res);

  // Header
  doc.fontSize(20).fillColor("#1e293b").text("RefundRakshak Verified Evidence Pack", { align: "center" });
  doc.fontSize(10).fillColor("#64748b").text(`Case ID: ${caseState.case_id} | Generated: ${new Date().toISOString()}`, { align: "center" });
  doc.moveDown(1.5);

  // Section 1: Transaction Facts (Masked)
  doc.fontSize(14).fillColor("#0f172a").text("1. Transaction Details");
  doc.fontSize(10).fillColor("#334155");
  const facts = caseState.transaction_facts;
  const maskedRef = facts.transaction_reference
    ? "****" + facts.transaction_reference.slice(-4)
    : "N/A";
  doc.text(`Amount: ₹${facts.amount ?? "N/A"}`);
  doc.text(`Transaction Date: ${facts.transaction_date ?? "N/A"}`);
  doc.text(`Transaction Reference: ${maskedRef}`);
  doc.text(`Bank / Provider: ${facts.bank_or_provider ?? "N/A"}`);
  doc.text(`Transaction Status: ${facts.transaction_status ?? "N/A"}`);
  doc.text(`Beneficiary Status: ${facts.beneficiary_status ?? "N/A"}`);
  doc.moveDown(1);

  // Section 2: Classification & Rule Source
  doc.fontSize(14).fillColor("#0f172a").text("2. Grievance Classification & Rule Source");
  doc.fontSize(10).fillColor("#334155");
  doc.text(`Classification: ${caseState.classification ?? "Pending"}`);
  doc.text(`Branch: ${caseState.branch}`);
  doc.text(`Rationale: ${caseState.classification_rationale}`);
  if (caseState.source_references && caseState.source_references.length > 0) {
    const src = caseState.source_references[0];
    doc.text(`Rule Title: ${src.title}`);
    doc.text(`Issuer & Date: ${src.issuer} (${src.circular_or_scheme_date})`);
    doc.text(`Official URL: ${src.official_url}`);
  }
  doc.moveDown(1);

  // Section 3: Timeline & Complaint History
  doc.fontSize(14).fillColor("#0f172a").text("3. Timeline & Complaint History");
  doc.fontSize(10).fillColor("#334155");
  (caseState.timeline || []).forEach((t: any) => {
    doc.text(`• [${new Date(t.timestamp).toLocaleDateString()}] ${t.event}`);
  });
  doc.moveDown(1);

  // Section 4: Disclaimers & Required Lines
  doc.fontSize(12).fillColor("#0f172a").text("Disclaimers & Notices");
  doc.fontSize(9).fillColor("#64748b");
  doc.text("• Generated by RefundRakshak prototype");
  doc.text("• Not legal advice");
  doc.text("• Not proof of submission");
  doc.text("• Potential compensation estimate, subject to verification.");

  doc.end();
}
